### PR TITLE
Mouse controls

### PR DESCRIPTION
**Pull request by cquammen**
Basic mouse controls added.

### CODE REVIEW

**Comment by cquammen** [comment]
Is this the right camera model? The direction of rotation in x reverses when you rotate vertically so that the objects in the scene are upside down.

**Comment by demarle** [comment]
In my raw excitement to see it work I merged instantaneously before even trying it locally.
Trying it with pv_slice_data didn't work.
Traceback (most recent call last):
  File "/Source/CINEMA/Cinema-basic/qtviewer/RenderViewMouseInteractor.py", line 54, in onMouseMove
    self._theta = self._incrementAngle(self._theta, theta_sign, self._thetaValues)
  File "/Source/CINEMA/Cinema-basic/qtviewer/RenderViewMouseInteractor.py", line 64, in _incrementAngle
    index = angles.index(angle)
ValueError: 0 is not in list
What data set were you working with?

**Comment by cquammen** [comment]
Oops. Haven't made it work with a store that doesn't have phi and theta values. I will do that. I tested against the wavelet store you emailed most recently.

**Comment by demarle** [comment]
Camera doesn't match the web viewer yet. When I start both and move the slice slider the orientation axes suddenly flip in the Qt viewer.
Other things:
phi and theta sliders don't work now.
We'll need to see the value as text with each slider.

**Pull request merged**
